version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      capacitor:
        patterns:
          - "@capacitor/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
